INSERT INTO LIGHT (ID, LEVEL, STATUS) VALUES (1, 20,'ON');
INSERT INTO NOISE (ID, LEVEL, STATUS) VALUES (1, 30,'ON');
INSERT INTO ROOM (ID, LIGHT_ID, NOISE_ID) VALUES (1, 1, 1);

INSERT INTO LIGHT (ID, LEVEL, STATUS) VALUES (2, 20,'ON');
INSERT INTO NOISE (ID, LEVEL, STATUS) VALUES (2, 30,'ON');
INSERT INTO ROOM (ID, LIGHT_ID, NOISE_ID) VALUES (2, 2, 2);

INSERT INTO LIGHT (ID, LEVEL, STATUS) VALUES (3, 20,'ON');
INSERT INTO NOISE (ID, LEVEL, STATUS) VALUES (3, 30,'ON');
INSERT INTO ROOM (ID, LIGHT_ID, NOISE_ID) VALUES (3, 3, 3);

INSERT INTO ROOM (ID, ROOMS) VALUES (1, (1,2,3));